# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'movistar+TechnicalTryout' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'ReachabilitySwift'
  pod 'Kingfisher'

  # Pods for movistar+TechnicalTryout

#  target 'movistar+TechnicalTryoutTests' do
#    inherit! :search_paths
#  end
#
#  target 'movistar+TechnicalTryoutUITests' do
#  end

end
